# Generated by Django 5.1.6 on 2025-02-19 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='email_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='github',
            field=models.CharField(blank=True, verbose_name='Github'),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='linked_in',
            field=models.CharField(blank=True, verbose_name='Linked-in'),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=12, verbose_name='Mobile Number'),
        ),
    ]
