# Generated by Django 5.1.6 on 2025-02-20 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]
        
