# Generated by Django 5.1.6 on 2025-02-19 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_personalinfo_email_id_personalinfo_github_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='educationInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, null=True, verbose_name='Education Name')),
                ('institute', models.CharField(blank=True, null=True, verbose_name='school or College Name')),
                ('specilization', models.CharField(blank=True, null=True, verbose_name='specilization')),
                ('join_date', models.DateField(blank=True, null=True, verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('marks', models.CharField(blank=True, verbose_name='Marks or Perecentage or GPA')),
            ],
        ),
    ]
