# Generated by Django 5.1.6 on 2025-02-20 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_certificateinfo_educationinfo_personalinfo_skillinfo_and_more'),
    ]