# Generated by Django 5.1.6 on 2025-02-19 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_educationinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='skillInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, null=True, verbose_name='Skill')),
            ],
        ),
    ]
