# Generated by Django 5.1.6 on 2025-02-20 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_certificateinfo_educationinfo_personalinfo_skillinfo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='projectinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name')),
                ('overview', models.TextField(blank=True, null=True, verbose_name='Overview')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('repository_link', models.URLField(blank=True, max_length=255, null=True, verbose_name='Repository Link')),
                ('status', models.CharField(choices=[('Ongoing', 'Ongoing'), ('Completed', 'Completed')], default='Completed', max_length=50, verbose_name='Status')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.category')),
                ('features', models.ManyToManyField(blank=True, to='home.feature')),
                ('technologies', models.ManyToManyField(blank=True, to='home.technology')),
            ],
        ),
        migrations.AlterField(
            model_name='feature',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_feature', to='home.projectinfo'),
        ),
        migrations.AlterField(
            model_name='processstep',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_step', to='home.projectinfo'),
        ),
        migrations.DeleteModel(
            name='ProjectsInfo',
        ),
    ]
