# Generated by Django 5.1.6 on 2025-02-20 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_certificateinfo_educationinfo_personalinfo_skillinfo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, null=True, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='educationInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, null=True, verbose_name='Education Name')),
                ('institute', models.CharField(blank=True, null=True, verbose_name='school or College Name')),
                ('specilization', models.CharField(blank=True, null=True, verbose_name='specilization')),
                ('join_date', models.DateField(blank=True, null=True, verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('marks', models.CharField(blank=True, verbose_name='Marks or Perecentage or GPA')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='First Name')),
                ('middle_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Middle Name')),
                ('last_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Last Name')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='DOB')),
                ('mobile_number', models.CharField(blank=True, max_length=12, verbose_name='Mobile Number')),
                ('email_id', models.CharField(blank=True, max_length=255, verbose_name='Email')),
                ('linked_in', models.CharField(blank=True, verbose_name='Linked-in')),
                ('github', models.CharField(blank=True, verbose_name='Github')),
            ],
        ),
        migrations.CreateModel(
            name='skillInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, null=True, verbose_name='Skill')),
            ],
        ),
        migrations.CreateModel(
            name='WebApplicationInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, null=True, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('technologies', models.TextField(blank=True, null=True, verbose_name='Technologies Used')),
            ],
        ),
        migrations.CreateModel(
            name='WorkexperienceInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, null=True, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('join_date', models.DateField(blank=True, null=True, verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
            ],
        ),
    ]
