# Generated by Django 5.1.6 on 2025-02-20 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_certificateinfo_educationinfo_personalinfo_skillinfo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='project_category', to='home.projectinfo'),
        ),
        migrations.AddField(
            model_name='technology',
            name='technology',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='project_technology', to='home.projectinfo'),
        ),
    ]
