# Generated by Django 5.1.6 on 2025-02-20 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_projectinfo_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category',
        ),
        migrations.RemoveField(
            model_name='technology',
            name='technology',
        ),
        migrations.AddField(
            model_name='category',
            name='project',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='proj_category', to='home.projectinfo'),
        ),
        migrations.AddField(
            model_name='technology',
            name='project',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='proj_technology', to='home.projectinfo'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='project',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='project_feature', to='home.projectinfo'),
        ),
        migrations.AlterField(
            model_name='processstep',
            name='project',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='project_step', to='home.projectinfo'),
        ),
    ]
