# Generated by Django 5.1.6 on 2025-02-20 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_remove_category_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectinfo',
            name='name',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Name'),
        ),
    ]
