# Generated by Django 5.1.6 on 2025-02-20 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_projectinfo_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectinfo',
            name='name',
            field=models.TextField(blank=True, null=True, verbose_name='Name'),
        ),
    ]
