# Generated by Django 5.1.6 on 2025-02-20 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_webapplicationinfo_github_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='image')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='home.personalinfo')),
            ],
        ),
    ]
