# Generated by Django 5.1.6 on 2025-02-20 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_profileimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='twitter',
            field=models.CharField(blank=True, verbose_name='Twitter'),
        ),
    ]
