# Generated by Django 5.1.6 on 2025-02-20 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_alter_feature_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='embedded_location',
            field=models.CharField(blank=True, verbose_name='Embedded Location'),
        ),
    ]
