# Generated by Django 5.1.6 on 2025-02-20 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_alter_personalinfo_embedded_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='objective',
            field=models.TextField(blank=True, verbose_name='Describe Yourself'),
        ),
    ]
